# Default configuration for LLM Text Processor

app_version: "0.5.4"

# General settings
general:
  output_dir: "processed_files"
  overwrite_existing: false
  preserve_original_filename: true
  file_extension_mapping:
    markdown: "md"
    plain_text: "txt"
    json: "json"
    csv: "csv"

# Processing settings
processing:
  parallel_processing: true
  max_workers: 4
  timeout_seconds: 300  # 5 minutes per file

# Structure preservation settings
structure:
  preserve_headings: true
  preserve_lists: true
  preserve_tables: true
  preserve_images: false  # Just descriptions, not the images themselves
  preserve_links: true
  preserve_emphasis: true
  preserve_code_blocks: true
  preserve_footnotes: true

# Format-specific settings
formats:
  pdf:
    extract_images: false
    ocr_on_images: false
    detect_columns: true
    handle_tables: true
    
  office:
    extract_comments: false
    extract_tracked_changes: false
    extract_hidden_content: false
    max_excel_rows: 1000
    max_excel_cols: 20
    
  web:
    remove_navigation: true
    remove_ads: true
    extract_main_content: true
    follow_links: false
    javascript_rendering: false
    
  text:
    detect_paragraphs: true
    detect_code_blocks: true
    respect_line_breaks: true

  csv:  # Added CSV format section
    delimiter: ","
    quotechar: "\""
    include_header: true
    max_rows: null  # null means no limit

# Output format settings
output:
  default_format: "markdown"  # Options: markdown, plain_text, json, csv
  include_metadata: true
  include_conversion_stats: true
  include_toc: true
  markdown:
    include_metadata: true
    metadata_position: "end"

# Metrics and reporting
metrics:
  estimate_token_count: true
  calculate_reduction_ratio: true
  log_level: "info"  # Options: debug, info, warning, error
  generate_report: true

# Processor Configuration (Primary place for cleaning/optimization flags)
processors:
  # Configuration for the content cleaner processor
  content_cleaner:
    remove_headers_footers: true
    remove_page_numbers: true
    remove_watermarks: false
    clean_whitespace: true
    normalize_unicode: true
    remove_boilerplate: true
    remove_duplicate_content: true
    remove_irrelevant_metadata: false
    merge_short_paragraphs: true
    remove_footnotes: true
    join_paragraph_lines: true

  # Configuration for the content optimizer processor
  content_optimizer:
    abbreviate_common_terms: true
    simplify_citations: true
    simplify_references: false
    simplify_urls: true
    max_line_length: 0
    simplify_vocabulary: true
    min_word_length: 4
    condense_repetitive_patterns: true
    remove_redundant_phrases: true
    remove_excessive_punctuation: true
    domain_abbreviations: []

  # Configuration for the structure processor
  structure_processor:
    pass
